server:
  port: 9001
spring:
  application:
    name: auth

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost

management:
  tracing:
    sampling:
      probability: 1.0
jwt:
  secret: VFUTIILXDe4eTjsqyF8LnvQIvCdepIR0GjoCoQ02xVeF2ru668IJrTSZFAGv5OR
  expiration: 60000