spring:
  kafka:
    bootstrap-servers: localhost:9092
  application:
    name: kafka

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost

management:
  tracing:
    sampling:
      probability: 1.0
