spring:
  application:
    name: eureka-server

server:
  port:
    8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: localhost

management:
  tracing:
    sampling:
      probability: 1.0

