server:
  port: 8082

spring:
  application:
    name: donation
  threads:
    virtual:
      enabled: true
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/donation_db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost

management:
  tracing:
    sampling:
      probability: 1.0