version: '3'

services:
  postgresql-master:
    image: 'bitnami/postgresql:latest'
    container_name: user_db_master
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=replica
      - POSTGRESQL_REPLICATION_PASSWORD=replica
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=admin
      - POSTGRESQL_DATABASE=user_db
      - POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=on
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
    networks:
      - postgres
    restart: unless-stopped

  postgresql-slave_1:
    image: 'bitnami/postgresql:latest'
    container_name: user_db_replica
    ports:
      - '5434:5434'
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=replica
      - POSTGRESQL_REPLICATION_PASSWORD=replica
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=admin
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:

