server:
  port: 9297


spring:
  application:
    name: config

  cloud:
    config:
      server:
        git:
          uri: http://github.com/Devast-PT/demo-config-server-sd_t2.git
          clone-on-start: true
      discovery:
        enabled: true

logging:
  level:
    org:
      springframework:
        cloud:
          config: debug